SOURCE: SYNTHIA
TARGET: Mapillary
NUM_CLASSES: 7
DATA_LIST_TARGET: ../dataset/mapillary_list/{}.txt
DATA_DIRECTORY_TARGET: ../../data/Mapillary
EXP_NAME: SYNTHIA2Mapillary_DeepLabv2_DADA_7classes
NUM_WORKERS: 4
USE_DEPTH: True
TRAIN:
  DA_METHOD: DADA
  SET_TARGET: train
  INFO_TARGET: ../dataset/mapillary_list/info.json
  INPUT_SIZE_TARGET:
    - 640 #1024
    - 320 #768
  MODEL: DeepLabv2_depth
  RESTORE_FROM: ../../pretrained_models/DeepLab_resnet_pretrained_imagenet.pth
TEST:
  MODE: best
  SET_TARGET: validation
  INFO_TARGET: ../dataset/mapillary_list/info.json
  INPUT_SIZE_TARGET:
    - 640 #1024
    - 320 #768