SOURCE: SYNTHIA
TARGET: Cityscapes
EXP_NAME: SYNTHIA2Cityscapes_DeepLabv2_AdvEnt
NUM_WORKERS: 4
USE_DEPTH: False
TRAIN:
  DA_METHOD: AdvEnt
  MODEL: DeepLabv2
  RESTORE_FROM: ../../pretrained_models/DeepLab_resnet_pretrained_imagenet.pth
TEST:
  MODE: best
  MODEL:
    - DeepLabv2